name: Deploy Website

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install NodeJS
    - uses:  action/setup-node@v2-beta
    
      with:
            node-version: 12
    - name: Install Surge    
      run: npm install -g surge
      
    - name: Run Surge
      run: surge ./ bootcamp_c_1_mirza.surge.sh --token ${{ secrets.DEPLOY_SECRET }}
      
        
